apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-worker-operator
spec:
  replicas: 1
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: cwm-worker-operator
  strategy:
{{ $.Values.strategy | indent 4 }}
  template:
    metadata:
      labels:
        app: cwm-worker-operator
    spec:
      {{ if $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{ $.Values.imagePullSecrets | indent 6 }}
      {{ end }}
      {{- if $.Values.tolerations }}
      tolerations:
      {{ toYaml $.Values.tolerations | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      serviceAccountName: cwm-worker-operator
      containers:
{{ range $.Values.operator.daemons }}
      - name: {{ . }}
        {{ if eq . "debug" }}
        command: ["sleep", "86400"]
        {{ else }}
        args: [{{ . | quote }}, "start_daemon"]
        {{ end }}
        image: {{ $.Values.operator.image }}:{{ $.Values.operator.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.operator.imagePullPolicy }}
        env:
        - name: CWM_API_URL
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"CWM_API_URL"}}
        - name: PACKAGES_READER_GITHUB_USER
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"PACKAGES_READER_GITHUB_USER"}}
        - name: PACKAGES_READER_GITHUB_TOKEN
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"PACKAGES_READER_GITHUB_TOKEN"}}
        {{ if $.Values.debug }}
        - name: DEBUG
          value: "yes"
        - name: DEBUG_VERBOSITY
          value: {{ $.Values.debugVerbosity | quote }}
        {{ end }}
        - name: REDIS_HOST
          value: {{ $.Values.operator.REDIS_HOST | quote }}
        - name: REDIS_PORT
          value: {{ $.Values.operator.REDIS_PORT | quote }}
        - name: REDIS_POOL_MAX_CONNECTIONS
          value: {{ $.Values.operator.REDIS_POOL_MAX_CONNECTIONS | quote }}
        - name: REDIS_POOL_TIMEOUT
          value: {{ $.Values.operator.REDIS_POOL_TIMEOUT | quote }}
        - name: CWM_ZONE
          value: {{ $.Values.cwm_zone | quote }}
        - name: INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS
          value: {{ $.Values.operator.DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS | quote }}
        - name: DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON
          value: {{ $.Values.operator.CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON | quote }}
        - name: MINIO_EXTRA_CONFIG_JSON
          value: {{ $.Values.operator.MINIO_EXTRA_CONFIG_JSON | quote }}
        - name: CWM_WORKER_EXTRA_OBJECTS_JSON
          value: {{ $.Values.operator.CWM_WORKER_EXTRA_OBJECTS_JSON | quote }}
        - name: CACHE_MINIO_VERSIONS
          value: {{ $.Values.operator.CACHE_MINIO_VERSIONS | quote }}
        - name: PROMETHEUS_METRICS_PORT_INITIALIZER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_INITIALIZER | quote }}
        - name: PROMETHEUS_METRICS_PORT_DEPLOYER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_DEPLOYER | quote }}
        - name: PROMETHEUS_METRICS_PORT_WAITER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_WAITER | quote }}
        - name: PROMETHEUS_METRICS_PORT_UPDATER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_UPDATER | quote }}
        - name: PROMETHEUS_METRICS_PORT_DELETER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_DELETER | quote }}
        - name: PROMETHEUS_METRICS_PORT_METRICS_UPDATER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_METRICS_UPDATER | quote }}
        {{ if $.Values.operator.PROMETHEUS_METRICS_WITH_DOMAIN_LABEL }}
        - name: PROMETHEUS_METRICS_WITH_DOMAIN_LABEL
          value: "yes"
        {{ end }}
        - name: DELETER_DEFAULT_DELETE_NAMESPACE
          value: {{ if $.Values.operator.DELETER_DEFAULT_DELETE_NAMESPACE }}"yes"{{ else }}"no"{{ end }}
        - name: DELETER_DEFAULT_DELETE_HELM
          value: {{ if $.Values.operator.DELETER_DEFAULT_DELETE_HELM }}"yes"{{ else }}"no"{{ end }}
        - name: DEPLOYER_USE_EXTERNAL_SERVICE
          value: {{ if $.Values.operator.DEPLOYER_USE_EXTERNAL_SERVICE }}"yes"{{ else }}"no"{{ end }}
        - name: DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS
          value: {{ if $.Values.operator.DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS }}"yes"{{ else }}"no"{{ end }}
        - name: DELETER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.DELETER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: FORCE_UPDATE_MAX_HOURS_TTL
          value: {{ $.Values.operator.FORCE_UPDATE_MAX_HOURS_TTL | quote }}
        - name: UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: WAITER_VERIFY_WORKER_ACCESS
          value: {{ if $.Values.operator.WAITER_VERIFY_WORKER_ACCESS }}"yes"{{ else }}"no"{{ end }}
        - name: WORKER_ERROR_MAX_ATTEMPTS
          value: {{ $.Values.operator.WORKER_ERROR_MAX_ATTEMPTS | quote }}
        - name: FORCE_DELETE_GRACE_PERIOD_HOURS
          value: {{ $.Values.operator.FORCE_DELETE_GRACE_PERIOD_HOURS | quote }}
        - name: LAST_ACTION_LOGGER_UPDATE_GRACE_PERIOD_SECONDS
          value: {{ $.Values.operator.LAST_ACTION_LOGGER_UPDATE_GRACE_PERIOD_SECONDS | quote }}
        - name: METRICS_LOGGER_DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS
          value: {{ $.Values.operator.METRICS_LOGGER_DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS | quote }}
        - name: PROMETHEUS_URL
          value: {{ $.Values.operator.PROMETHEUS_URL | quote }}
        - name: METRICS_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.METRICS_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: FORCE_DELETE_IF_NO_ACTION_FOR_MINUTES
          value: {{ $.Values.operator.FORCE_DELETE_IF_NO_ACTION_FOR_MINUTES | quote }}
        - name: WEB_UI_PORT
          value: {{ $.Values.operator.WEB_UI_PORT | quote }}
{{ $.Values.operator.env | indent 8 }}
        resources:
{{ $.Values.operator.resources | indent 10 }}
{{ end }}
