{{ range $.Values.operator.daemons }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-worker-operator-{{ . }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: cwm-worker-operator-{{ . }}
  strategy:
{{ $.Values.strategy | indent 4 }}
  template:
    metadata:
      labels:
        app: cwm-worker-operator-{{ . }}
      {{ if eq . "web-ui" }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/web-ui-nginx-configmap.yaml") . | sha256sum }}
      {{ end }}
    spec:
      {{- if $.Values.tolerations }}
      tolerations:
{{ toYaml $.Values.tolerations | indent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      enableServiceLinks: false
      serviceAccountName: cwm-worker-operator
      volumes:
      - name: data
        {{ if $.Values.enableOperatorPvc }}
        persistentVolumeClaim:
          claimName: cwm-worker-operator
        {{ else }}
        emptyDir: {}
        {{ end }}
      - name: config
        configMap:
          name: web-ui-nginx
      containers:
      - name: {{ . }}
        {{ if eq . "debug" }}
        command: ["sleep", "86400"]
        {{ else }}
        args: [{{ . | quote }}, "start_daemon"]
        {{ end }}
        image: {{ $.Values.operator.image }}:{{ $.Values.operator.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ $.Values.operator.imagePullPolicy }}
        {{ if eq . "disk-usage-updater" }}
        securityContext:
          privileged: true
        {{ end }}
        env:
        - name: CWM_API_URL
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"CWM_API_URL"}}
        - name: CWM_API_KEY
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"CWM_API_KEY"}}
        - name: CWM_API_SECRET
          valueFrom: {"secretKeyRef":{"name":"cwm-worker-operator", "key":"CWM_API_SECRET"}}
        {{ if $.Values.debug }}
        - name: DEBUG
          value: "yes"
        - name: DEBUG_VERBOSITY
          value: {{ $.Values.debugVerbosity | quote }}
        {{ end }}
        - name: INGRESS_REDIS_HOST
          value: {{ $.Values.operator.INGRESS_REDIS_HOST | quote }}
        - name: INGRESS_REDIS_PORT
          value: {{ $.Values.operator.INGRESS_REDIS_PORT | quote }}
        - name: INGRESS_REDIS_POOL_MAX_CONNECTIONS
          value: {{ $.Values.operator.INGRESS_REDIS_POOL_MAX_CONNECTIONS | quote }}
        - name: INGRESS_REDIS_POOL_TIMEOUT
          value: {{ $.Values.operator.INGRESS_REDIS_POOL_TIMEOUT | quote }}
        - name: INGRESS_REDIS_DB
          value: {{ $.Values.operator.INGRESS_REDIS_DB | quote }}
        - name: INTERNAL_REDIS_HOST
          value: {{ $.Values.operator.INTERNAL_REDIS_HOST | quote }}
        - name: INTERNAL_REDIS_PORT
          value: {{ $.Values.operator.INTERNAL_REDIS_PORT | quote }}
        - name: INTERNAL_REDIS_POOL_MAX_CONNECTIONS
          value: {{ $.Values.operator.INTERNAL_REDIS_POOL_MAX_CONNECTIONS | quote }}
        - name: INTERNAL_REDIS_POOL_TIMEOUT
          value: {{ $.Values.operator.INTERNAL_REDIS_POOL_TIMEOUT | quote }}
        - name: INTERNAL_REDIS_DB
          value: {{ $.Values.operator.INTERNAL_REDIS_DB | quote }}
        - name: METRICS_REDIS_HOST
          value: {{ $.Values.operator.METRICS_REDIS_HOST | quote }}
        - name: METRICS_REDIS_PORT
          value: {{ $.Values.operator.METRICS_REDIS_PORT | quote }}
        - name: METRICS_REDIS_POOL_MAX_CONNECTIONS
          value: {{ $.Values.operator.METRICS_REDIS_POOL_MAX_CONNECTIONS | quote }}
        - name: METRICS_REDIS_POOL_TIMEOUT
          value: {{ $.Values.operator.METRICS_REDIS_POOL_TIMEOUT | quote }}
        - name: METRICS_REDIS_DB
          value: {{ $.Values.operator.METRICS_REDIS_DB | quote }}
        - name: CWM_ZONE
          value: {{ $.Values.cwm_zone | quote }}
        - name: CWM_ADDITIONAL_ZONES
          value: {{ $.Values.cwm_additional_zones | quote }}
        - name: INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS
          value: {{ $.Values.operator.DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS | quote }}
        - name: DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON
          value: {{ $.Values.operator.CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON | quote }}
        - name: MINIO_EXTRA_CONFIG_JSON
          value: {{ $.Values.operator.MINIO_EXTRA_CONFIG_JSON | quote }}
        - name: CWM_WORKER_EXTRA_OBJECTS_JSON
          value: {{ $.Values.operator.CWM_WORKER_EXTRA_OBJECTS_JSON | quote }}
        - name: CACHE_MINIO_VERSIONS
          value: {{ $.Values.operator.CACHE_MINIO_VERSIONS | quote }}
        - name: PROMETHEUS_METRICS_PORT_INITIALIZER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_INITIALIZER | quote }}
        - name: PROMETHEUS_METRICS_PORT_DEPLOYER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_DEPLOYER | quote }}
        - name: PROMETHEUS_METRICS_PORT_WAITER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_WAITER | quote }}
        - name: PROMETHEUS_METRICS_PORT_UPDATER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_UPDATER | quote }}
        - name: PROMETHEUS_METRICS_PORT_DELETER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_DELETER | quote }}
        - name: PROMETHEUS_METRICS_PORT_METRICS_UPDATER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_METRICS_UPDATER | quote }}
        - name: PROMETHEUS_METRICS_PORT_DISK_USAGE_UPDATER
          value: {{ $.Values.operator.PROMETHEUS_METRICS_PORT_DISK_USAGE_UPDATER | quote }}
        {{ if $.Values.operator.PROMETHEUS_METRICS_WITH_IDENTIFIER }}
        - name: PROMETHEUS_METRICS_WITH_IDENTIFIER
          value: "yes"
        {{ end }}
        - name: DELETER_DEFAULT_DELETE_NAMESPACE
          value: {{ if $.Values.operator.DELETER_DEFAULT_DELETE_NAMESPACE }}"yes"{{ else }}"no"{{ end }}
        - name: DELETER_DEFAULT_DELETE_HELM
          value: {{ if $.Values.operator.DELETER_DEFAULT_DELETE_HELM }}"yes"{{ else }}"no"{{ end }}
        - name: DEPLOYER_USE_EXTERNAL_SERVICE
          value: {{ if $.Values.operator.DEPLOYER_USE_EXTERNAL_SERVICE }}"yes"{{ else }}"no"{{ end }}
        - name: DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS
          value: {{ if $.Values.operator.DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS }}"yes"{{ else }}"no"{{ end }}
        - name: DEPLOYER_MAX_ATTEMPT_NUMBERS
          value: {{ $.Values.operator.DEPLOYER_MAX_ATTEMPT_NUMBERS | quote }}
        - name: DEPLOYER_WAIT_DEPLOYMENT_ERROR_MAX_SECONDS
          value: {{ $.Values.operator.DEPLOYER_WAIT_DEPLOYMENT_ERROR_MAX_SECONDS | quote }}
        - name: DEPLOYER_MAX_PARALLEL_DEPLOY_PROCESSES
          value: {{ $.Values.operator.DEPLOYER_MAX_PARALLEL_DEPLOY_PROCESSES | quote }}
        - name: DELETER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.DELETER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: FORCE_UPDATE_MAX_HOURS_TTL
          value: {{ $.Values.operator.FORCE_UPDATE_MAX_HOURS_TTL | quote }}
        - name: UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: WAITER_VERIFY_WORKER_ACCESS
          value: {{ if $.Values.operator.WAITER_VERIFY_WORKER_ACCESS }}"yes"{{ else }}"no"{{ end }}
        - name: WORKER_ERROR_MAX_ATTEMPTS
          value: {{ $.Values.operator.WORKER_ERROR_MAX_ATTEMPTS | quote }}
        - name: FORCE_DELETE_GRACE_PERIOD_HOURS
          value: {{ $.Values.operator.FORCE_DELETE_GRACE_PERIOD_HOURS | quote }}
        - name: LAST_ACTION_LOGGER_UPDATE_GRACE_PERIOD_SECONDS
          value: {{ $.Values.operator.LAST_ACTION_LOGGER_UPDATE_GRACE_PERIOD_SECONDS | quote }}
        - name: METRICS_LOGGER_DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS
          value: {{ $.Values.operator.METRICS_LOGGER_DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS | quote }}
        - name: PROMETHEUS_URL
          value: {{ $.Values.operator.PROMETHEUS_URL | quote }}
        - name: METRICS_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.METRICS_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: FORCE_DELETE_IF_NO_ACTION_FOR_MINUTES
          value: {{ $.Values.operator.FORCE_DELETE_IF_NO_ACTION_FOR_MINUTES | quote }}
        - name: WEB_UI_PORT
          value: {{ $.Values.operator.WEB_UI_PORT | quote }}
        - name: DISK_USAGE_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.DISK_USAGE_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: DISK_USAGE_UPDATER_NFS_SERVER
          value: {{ $.Values.operator.DISK_USAGE_UPDATER_NFS_SERVER | quote }}
        - name: DISK_USAGE_UPDATER_NFS_ROOT_PATH
          value: {{ $.Values.operator.DISK_USAGE_UPDATER_NFS_ROOT_PATH | quote }}
        - name: ALERTER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.ALERTER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: ALERTER_SLACK_WEBHOOK_URL
          value: {{ $.Values.operator.ALERTER_SLACK_WEBHOOK_URL | quote }}
        - name: ALERTER_MESSAGE_PREFIX
          value: {{ $.Values.operator.ALERTER_MESSAGE_PREFIX | quote }}
        - name: CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: NODES_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.NODES_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: DNS_RECORDS_PREFIX
          value: {{ $.Values.operator.DNS_RECORDS_PREFIX | quote }}
        {{ if eq . "nodes-checker" }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ $.Values.operator.AWS_ACCESS_KEY_ID | quote }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ $.Values.operator.AWS_SECRET_ACCESS_KEY | quote }}
        - name: AWS_ROUTE53_HOSTEDZONE_ID
          value: {{ $.Values.operator.AWS_ROUTE53_HOSTEDZONE_ID | quote }}
        {{ end }}
        - name: AWS_ROUTE53_HOSTEDZONE_DOMAIN
          value: {{ $.Values.operator.AWS_ROUTE53_HOSTEDZONE_DOMAIN | quote }}
        - name: DUMMY_TEST_WORKER_ID
          value: {{ $.Values.operator.DUMMY_TEST_WORKER_ID | quote }}
        - name: DUMMY_TEST_HOSTNAME
          value: {{ $.Values.operator.DUMMY_TEST_HOSTNAME | quote }}
        - name: MOCK_GATEWAYS
          value: {{ $.Values.operator.MOCK_GATEWAYS | quote }}
        - name: DEPLOYER_WITH_HELM_DRY_RUN
          value: {{ if $.Values.operator.DEPLOYER_WITH_HELM_DRY_RUN }}"yes"{{ else }}"no"{{ end }}
        - name: CLEAR_CACHER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.CLEAR_CACHER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: UPDATER_DEFAULT_LAST_UPDATE_DATETIME_SECONDS
          value: {{ $.Values.operator.UPDATER_DEFAULT_LAST_UPDATE_DATETIME_SECONDS | quote }}
        - name: DHPARAM_KEY
          value: {{ $.Values.operator.DHPARAM_KEY | quote }}
        - name: VOLUME_CONFIG_OVERRIDE_URL
          value: {{ $.Values.operator.VOLUME_CONFIG_OVERRIDE_URL | quote }}
        - name: VOLUME_CONFIG_OVERRIDE_USERNAME
          value: {{ $.Values.operator.VOLUME_CONFIG_OVERRIDE_USERNAME | quote }}
        - name: VOLUME_CONFIG_OVERRIDE_PASSWORD
          value: {{ $.Values.operator.VOLUME_CONFIG_OVERRIDE_PASSWORD | quote }}
        - name: NAS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.NAS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: NAS_IPS
          value: {{ $.Values.operator.NAS_IPS | quote }}
        - name: NAS_CHECKER_VOLUME_TEMPLATE_JSON
          value: {{ $.Values.operator.NAS_CHECKER_VOLUME_TEMPLATE_JSON | quote }}
        - name: LOCAL_STORAGE_PATH
          value: "/data"
        - name: REDIS_CLEANER_DELETE_FAILED_TO_DEPLOY_HOSTNAME_ERROR_MIN_SECONDS
          value: {{ $.Values.operator.REDIS_CLEANER_DELETE_FAILED_TO_DEPLOY_HOSTNAME_ERROR_MIN_SECONDS | quote }}
        - name: REDIS_CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.REDIS_CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
        - name: REDIS_CLEANER_DELETE_ANY_HOSTNAME_ERROR_MIN_SECONDS
          value: {{ $.Values.operator.REDIS_CLEANER_DELETE_ANY_HOSTNAME_ERROR_MIN_SECONDS | quote }}
        - name: WORKERS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS
          value: {{ $.Values.operator.WORKERS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS | quote }}
{{ $.Values.operator.env | indent 8 }}
        volumeMounts:
        - mountPath: "/data"
          name: "data"
        resources:
{{ if and (eq . "initializer") $.Values.operator.initializerResources }}
{{ toYaml $.Values.operator.initializerResources | indent 10 }}
{{ else if and (eq . "deployer") $.Values.operator.deployerResources }}
{{ toYaml $.Values.operator.deployerResources | indent 10 }}
{{ else if and (eq . "waiter") $.Values.operator.waiterResources }}
{{ toYaml $.Values.operator.waiterResources | indent 10 }}
{{ else if and (eq . "updater") $.Values.operator.updaterResources }}
{{ toYaml $.Values.operator.updaterResources | indent 10 }}
{{ else if and (eq . "deleter") $.Values.operator.deleterResources }}
{{ toYaml $.Values.operator.deleterResources | indent 10 }}
{{ else if and (eq . "metrics-updater") $.Values.operator.metricsUpdaterResources }}
{{ toYaml $.Values.operator.metricsUpdaterResources | indent 10 }}
{{ else if and (eq . "web-ui") $.Values.operator.webUiResources }}
{{ toYaml $.Values.operator.webUiResources | indent 10 }}
{{ else if and (eq . "disk-usage-updater") $.Values.operator.diskUsageUpdaterResources }}
{{ toYaml $.Values.operator.diskUsageUpdaterResources | indent 10 }}
{{ else if and (eq . "alerter") $.Values.operator.AlerterResources }}
{{ toYaml $.Values.operator.AlerterResources | indent 10 }}
{{ else if and (eq . "cleaner") $.Values.operator.CleanerResources }}
{{ toYaml $.Values.operator.CleanerResources | indent 10 }}
{{ else if and (eq . "nodes-checker") $.Values.operator.NodesCheckerResources }}
{{ toYaml $.Values.operator.NodesCheckerResources | indent 10 }}
{{ else if and (eq . "clear-cacher") $.Values.operator.ClearCacherResources }}
{{ toYaml $.Values.operator.ClearCacherResources | indent 10 }}
{{ else if and (eq . "nas-checker") $.Values.operator.NasCheckerResources }}
{{ toYaml $.Values.operator.NasCheckerResources | indent 10 }}
{{ else }}
{{ toYaml $.Values.operator.defaultResources | indent 10 }}
{{ end }}
      {{ if eq . "web-ui" }}
      - name: nginx
        # Pulled on Dec 1, 2021
        image: nginx@sha256:097c3a0913d7e3a5b01b6c685a60c03632fc7a2b50bc8e35bcaa3691d788226e
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/nginx/conf.d
      {{ end }}
---
{{ end }}
