apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-worker-operator-redis
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cwm-worker-operator-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cwm-worker-operator-redis
    spec:
      terminationGracePeriodSeconds: 5
      {{- if $.Values.tolerations }}
      tolerations:
{{ toYaml $.Values.tolerations | indent 6 }}
      {{- end }}
      containers:
      - name: redis
        image: {{ $.Values.redis.image }}
        imagePullPolicy: {{ $.Values.redis.imagePullPolicy }}
        {{ if $.Values.redis.persistence.enabled }}
        args: ["redis-server", "--appendonly", "yes"]
        {{ end }}
        resources:
{{ $.Values.redis.resources | indent 10 }}
        {{ if $.Values.redis.persistence.enabled }}
        volumeMounts:
        - mountPath: "/data"
          name: "data"
        {{ end }}
      volumes:
      - name: data
{{ $.Values.redis.persistence.volume | indent 8 }}
