apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwm-worker-operator-redis
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cwm-worker-operator-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cwm-worker-operator-redis
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: redis
        image: {{ $.Values.redis.image }}
        imagePullPolicy: {{ $.Values.redis.imagePullPolicy }}
        resources:
{{ $.Values.redis.resources | indent 10 }}
