apiVersion: v1
kind: Secret
metadata:
  name: cwm-worker-operator
type: generic
data:
  CWM_API_URL: {{ .Values.cwm_api_url | b64enc | quote }}
  CWM_API_KEY: {{ .Values.cwm_api_key | b64enc | quote }}
  CWM_API_SECRET: {{ .Values.cwm_api_secret | b64enc | quote }}
