apiVersion: v1
kind: Secret
metadata:
  name: cwm-worker-operator
type: generic
data:
  CWM_API_URL: {{ .Values.cwm_api_url | b64enc | quote }}
  PACKAGES_READER_GITHUB_USER: {{ .Values.packages_reader_github_user | b64enc | quote }}
  PACKAGES_READER_GITHUB_TOKEN: {{ .Values.packages_reader_github_token | b64enc | quote }}
