debug: true
debugVerbosity: 10
revisionHistoryLimit: 2
terminationGracePeriodSeconds: 30
cwm_api_url: ""
cwm_api_key: ""
cwm_api_secret: ""
cwm_zone: "EU"
cwm_additional_zones: ""
#tolerations: []

ingressRedis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "25m"
      memory: "50Mi"
    limits:
      memory: "200Mi"
  persistence:
    enabled: true

internalRedis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "25m"
      memory: "50Mi"
    limits:
      memory: "200Mi"
  persistence:
    enabled: true

metricsRedis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "25m"
      memory: "50Mi"
    limits:
      memory: "200Mi"
  persistence:
    enabled: true

operator:
  daemons:
    - initializer
    - deployer
    - waiter
    - updater
    - deleter
    - metrics-updater
    - web-ui
    - disk-usage-updater
    - alerter
    - cleaner
    - nodes-checker
    - clear-cacher
    - nas-checker
    - redis-cleaner
    - workers-checker
    - throttler
  image: ghcr.io/cloudwebmanage/cwm-worker-operator/cwm_worker_operator
  tag: ""
  imagePullPolicy: IfNotPresent
  # comma-separated list of minio versions to ensure cache exists for on startup
  CACHE_MINIO_VERSIONS: ""
  INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "0.01"
  DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS: "30"
  DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "2"
  CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON: "{}"
  MINIO_EXTRA_CONFIG_JSON: "{}"
  CWM_WORKER_EXTRA_OBJECTS_JSON: "[]"
  # all must use the same port, which must be same as serviceMonitorsPort
  PROMETHEUS_METRICS_PORT_INITIALIZER: "8081"
  PROMETHEUS_METRICS_PORT_DEPLOYER: "8081"
  PROMETHEUS_METRICS_PORT_WAITER: "8081"
  PROMETHEUS_METRICS_PORT_DELETER: "8081"
  PROMETHEUS_METRICS_PORT_UPDATER: "8081"
  PROMETHEUS_METRICS_PORT_METRICS_UPDATER: "8081"
  PROMETHEUS_METRICS_PORT_DISK_USAGE_UPDATER: "8081"
  PROMETHEUS_METRICS_PORT_NAS_CHECKER: "8081"
  PROMETHEUS_METRICS_PORT_WORKERS_CHECKER: "8081"
  PROMETHEUS_METRICS_WITH_IDENTIFIER: false
  DELETER_DEFAULT_DELETE_NAMESPACE: false
  DELETER_DEFAULT_DELETE_HELM: true
  DELETER_DATA_DELETE_CONFIG_JSON: '{}'
  DEPLOYER_USE_EXTERNAL_SERVICE: false
  DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS: false
  DEPLOYER_MAX_ATTEMPT_NUMBERS: 10
  DEPLOYER_WAIT_DEPLOYMENT_ERROR_MAX_SECONDS: 2
  DEPLOYER_MAX_PARALLEL_DEPLOY_PROCESSES: 2
  INGRESS_REDIS_HOST: "cwm-worker-operator-redis-ingress.default.svc.cluster.local"
  INGRESS_REDIS_PORT: "6379"
  INGRESS_REDIS_POOL_MAX_CONNECTIONS: "50"
  INGRESS_REDIS_POOL_TIMEOUT: "5"
  INGRESS_REDIS_DB: "0"
  INTERNAL_REDIS_HOST: "cwm-worker-operator-redis-internal.default.svc.cluster.local"
  INTERNAL_REDIS_PORT: "6379"
  INTERNAL_REDIS_POOL_MAX_CONNECTIONS: "50"
  INTERNAL_REDIS_POOL_TIMEOUT: "5"
  INTERNAL_REDIS_DB: "0"
  METRICS_REDIS_HOST: "cwm-worker-operator-redis-metrics.default.svc.cluster.local"
  METRICS_REDIS_PORT: "6379"
  METRICS_REDIS_POOL_MAX_CONNECTIONS: "50"
  METRICS_REDIS_POOL_TIMEOUT: "5"
  METRICS_REDIS_DB: "0"
  DELETER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "1"
  FORCE_UPDATE_MAX_HOURS_TTL: "24"
  UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "5"
  WAITER_VERIFY_WORKER_ACCESS: true
  WAITER_MAX_PARALLEL_DEPLOY_PROCESSES: 2
  WORKER_ERROR_MAX_ATTEMPTS: "5"
  FORCE_DELETE_GRACE_PERIOD_HOURS: "1"
  LAST_ACTION_LOGGER_UPDATE_GRACE_PERIOD_SECONDS: "300"
  METRICS_LOGGER_DEPLOYMENT_API_METRICS_FLUSH_INTERVAL_SECONDS: "300"
  PROMETHEUS_URL: "http://localhost:9090"
  METRICS_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "1"
  FORCE_DELETE_IF_NO_ACTION_FOR_MINUTES: "30"
  WEB_UI_PORT: "8182"
  DISK_USAGE_UPDATER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "30"
  DISK_USAGE_UPDATER_NFS_SERVER: "cwm-nfs"
  DISK_USAGE_UPDATER_NFS_ROOT_PATH: "/ganesha-ceph/eu-vobjstore001"
  ALERTER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "15"
  ALERTER_SLACK_WEBHOOK_URL: ""
  ALERTER_MESSAGE_PREFIX: ""
  CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "900"
  NODES_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "60"
  DNS_RECORDS_PREFIX: "cwmc-operator-test"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ROUTE53_HOSTEDZONE_ID: ""
  AWS_ROUTE53_HOSTEDZONE_DOMAIN: ""
  DUMMY_TEST_WORKER_ID: "cwdummytst"
  DUMMY_TEST_HOSTNAME: "cwdummytst.example007.com"
  MOCK_GATEWAYS: "{}"
  DEPLOYER_WITH_HELM_DRY_RUN: false
  CLEAR_CACHER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "5"
  UPDATER_DEFAULT_LAST_UPDATE_DATETIME_SECONDS: "7200"
  UPDATER_MAX_PARALLEL_DEPLOY_PROCESSES: "2"
  DHPARAM_KEY: |
    -----BEGIN DH PARAMETERS-----
    MIIBCAKCAQEAuueQU6VmApLtG08PRJiq5nBrBPoieQ0MhAI3jZAuahu0AnQ/nnio
    aIfCvnnwilebPID8/a9iFzzqkcZWwAK/OaYn2p6t/9mfyYFVkWI394rCXTjXp8qa
    l5fl0cEzQT5erIi+UKKjFw1jirmigriLPzM+JvZUTzvkpeI7QNiFirg6Oq6IZiM+
    +sIqeaCWA3ughSIzcKQ/w6qNjPTrDHbxc41AZS1o5xzngmMGHBl0Nw7kvd0b6tZN
    I1ZLzZKeEApAE5f8z8eDdGXDbHaCd7bs9qhak7xUQNs8wEomV8F8rYDBnCwAKZSD
    LsHbKShgAFY7jHqIwkMm3N89kIqkQgrswwIBAg==
    -----END DH PARAMETERS-----
  VOLUME_CONFIG_OVERRIDE_URL: ""
  VOLUME_CONFIG_OVERRIDE_USERNAME: ""
  VOLUME_CONFIG_OVERRIDE_PASSWORD: ""
  NAS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "5"
  NAS_IPS: "1.2.3.4,5.6.7.8"
  # __NAS_IP__ in the template json will be replaced for each nas ip in NAS_IPS
  NAS_CHECKER_VOLUME_TEMPLATE_JSON: '{"emptyDir": {}}'
  NAS_CHECKER_WITH_KUBELET_LOGS: false
  NAS_CHECKER_NAMESPACE: "default"
  REDIS_CLEANER_DELETE_FAILED_TO_DEPLOY_HOSTNAME_ERROR_MIN_SECONDS: 120
  REDIS_CLEANER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: 5
  REDIS_CLEANER_DELETE_ANY_HOSTNAME_ERROR_MIN_SECONDS: 86400
  WORKERS_CHECKER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: 5
  WORKERS_CHECKER_MAX_PARALLEL_DEPLOY_PROCESSES: 2
  WORKERS_CHECKER_ALERT_POD_PENDING_SECONDS: 15
  WORKERS_CHECKER_ALERT_POD_MISSING_SECONDS: 10
  WORKERS_CHECKER_ALERT_NAMESPACE_TERMINATING_SECONDS: 120
  WORKERS_CHECKER_ALERT_INVALID_WORKER_SECONDS: 10
  THROTTLER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: 1
  THROTTLER_THROTTLE_PERIOD_SECONDS: 5
  THROTTLER_THROTTLE_MAX_REQUESTS: "10000000"
  THROTTLER_CHECK_TTL_SECONDS: 10
  env: ""
#  initializerResources: {}
#  deployerResources: {}
#  waiterResources: {}
#  updaterResources: {}
#  deleterResources: {}
#  metricsUpdaterResources: {}
#  webUiResources: {}
#  diskUsageUpdaterResources: {}
#  AlerterResources: {}
#  CleanerResources: {}
#  NodesCheckerResources: {}
#  NasCheckerResources: {}
  defaultResources:
    requests:
      cpu: "25m"
      memory: "50Mi"
    limits:
      memory: "200Mi"
  webUiReplicas: 1

# each object have required attributes: apiVersion, kind, name, spec
extraObjects: []

redisCommander:
  enabled: true
  # Pulled Oct 6, 2021
  image: rediscommander/redis-commander@sha256:19cd0c49f418779fa2822a0496c5e6516d0c792effc39ed20089e6268477e40a
  resources:
    requests: { cpu: "25m", memory: "50Mi" }
    limits: { memory: "200Mi" }
  ingress:
    enabled: false
    httpAuthSecretName: ""
    domain: ""

webUiIngress:
  enabled: false
  httpAuthSecretName: ""
  domain: ""

enableRedisPvc: false
enableOperatorPvc: false
storageClassName: ""

enableServiceMonitor: false
serviceMonitorsPort: 8081
serviceMonitors:
  - initializer
  # deployer, waiter and updater don't send metrics at the moment because they use the multiprocessor
  # - deployer
  # - waiter
  # - updater
  - deleter
  - metrics-updater
  - disk-usage-updater
  - nas-checker
  - workers-checker
