debug: true
debugVerbosity: 10
revisionHistoryLimit: 2
terminationGracePeriodSeconds: 30
strategy: |
  type: Recreate
imagePullSecrets: |
  - name: github
cwm_api_url: ""
cwm_zone: "EU"
packages_reader_github_user: ""
packages_reader_github_token: ""

redis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources: |
    requests:
      cpu: .05
      memory: 50Mi
    limits:
      memory: 200Mi
  persistence:
    enabled: true
    volume: |
      emptyDir: {}

operator:
  daemons: ["initializer", "deployer", "waiter"]
  image: docker.pkg.github.com/cloudwebmanage/cwm-worker-operator/cwm_worker_operator
  tag: ""
  imagePullPolicy: IfNotPresent
  # comma-separated list of minio versions to ensure cache exists for on startup
  CACHE_MINIO_VERSIONS: ""
  INITIALIZER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "0.01"
  DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS: "30"
  DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "2"
  CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON: "{}"
  MINIO_EXTRA_CONFIG_JSON: "{}"
  CWM_WORKER_EXTRA_OBJECTS_JSON: "[]"
  PROMETHEUS_METRICS_PORT_INITIALIZER: "8081"
  PROMETHEUS_METRICS_PORT_DEPLOYER: "8082"
  PROMETHEUS_METRICS_PORT_WAITER: "8083"
  PROMETHEUS_METRICS_WITH_DOMAIN_LABEL: false
  DELETER_DEFAULT_DELETE_NAMESPACE: false
  DELETER_DEFAULT_DELETE_HELM: true
  DEPLOYER_USE_EXTERNAL_SERVICE: false
  DEPLOYER_USE_EXTERNAL_EXTRA_OBJECTS: false
  env: ""
  resources: |
    requests:
      cpu: .1
      memory: 100Mi
    limits:
      memory: 800Mi

# each object have required attributes: apiVersion, kind, name, spec
extraObjects: []
