debug: true
debugVerbosity: 10
revisionHistoryLimit: 2
terminationGracePeriodSeconds: 30
strategy: |
  type: Recreate
imagePullSecrets: |
  - name: github
cwm_api_url: ""
cwm_zone: "EU"
packages_reader_github_user: ""
packages_reader_github_token: ""

redis:
  image: redis@sha256:09c33840ec47815dc0351f1eca3befe741d7105b3e95bc8fdb9a7e4985b9e1e5
  imagePullPolicy: IfNotPresent
  resources: |
    requests:
      cpu: .05
      memory: 50Mi
    limits:
      memory: 200Mi
  persistence:
    enabled: true
    volume: |
      emptyDir: {}

operator:
  daemons: ["deployer", "errorhandler"]
  image: docker.pkg.github.com/cloudwebmanage/cwm-worker-operator/cwm_worker_operator
  tag: ""
  imagePullPolicy: IfNotPresent
  DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS: "30"
  ERRORHANDLER_WAIT_DEPLOYMENT_READY_MAX_SECONDS: "30"
  ERRORHANDLER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "2.0"
  DEPLOYER_SLEEP_TIME_BETWEEN_ITERATIONS_SECONDS: "2.0"
  CWM_WORKER_DEPLOYMENT_EXTRA_CONFIG_JSON: "{}"
  MINIO_EXTRA_CONFIG_JSON: "{}"
  env: ""
  resources: |
    requests:
      cpu: .1
      memory: 100Mi
    limits:
      memory: 800Mi

# each object have required attributes: apiVersion, kind, name, spec
extraObjects: []
