name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGES_READER_GITHUB_TOKEN: ${{ secrets.PACKAGES_READER_GITHUB_TOKEN }}
        PACKAGES_READER_GITHUB_USER: ${{ secrets.PACKAGES_READER_GITHUB_USER }}
        CWM_WORKER_HELM_DEPLOY_KEY: ${{ secrets.CWM_WORKER_HELM_DEPLOY_KEY }}
        CWM_API_URL: ${{ secrets.CWM_API_URL }}
      run: |
        sudo bin/install_minikube.sh && minikube version &&\
        bin/minikube_start.sh &&\
        sudo bin/install_kubectl.sh && kubectl version --client &&\
        sudo bin/install_helm.sh && helm version &&\
        sudo bin/install_python.sh &&\
        sudo bin/install_redis_cli.sh &&\
        bin/python_init_venv_requirements_module.sh &&\
        bin/redis_start_wait.sh &&\
        bin/minikube_wait.sh &&\
        . venv/bin/activate &&\
        export DEBUG=yes &&\
        export DEBUG_VERBOSITY=10 &&\
        export REDIS_HOST=172.17.0.1 &&\
        export CWM_ZONE=EU &&\
        export DEPLOYER_WAIT_DEPLOYMENT_READY_MAX_SECONDS="30.0" &&\
        export CWM_WORKER_DEPLOYMENT_HELM_CACHE_DIR="$(pwd)/.cwm_worker_deployment_helm_cache" &&\
        export CACHE_MINIO_VERSIONS=0.0.0-20200829T091900,0.0.0-20200910T100633 &&\
        export WAITER_VERIFY_WORKER_ACCESS=no &&\
        echo running python tests &&\
        tests/run_tests.sh &&\
        bin/docker_login.sh &&\
        bin/docker_build.sh &&\
        echo running docker tests &&\
        tests/docker_tests.sh &&\
        bin/docker_push_sha.sh &&\
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          bin/docker_push_latest.sh &&\
          bin/helm_init_deploy.sh &&\
          tests/k8s_tests.sh &&\
          bin/helm_publish.sh
        fi
